on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-builder-lint:unprivileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Flatpak repositories
        run: |
            flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
            flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
      - name: Allow unprivileged user namespaces
        run: sudo sysctl kernel.unprivileged_userns_clone=1
      - name: Setup Flatpak Builder
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: bottles.flatpak
          manifest-path: com.usebottles.bottles.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
        continue-on-error: true
        id: flatpak-builder
      - name: Upload logs on failure
        if: steps.flatpak-builder.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ./.flatpak-builder/build/*
          retention-days: 5
